ruleorder: create_ref_links_for_hic_alignment > bwa_mem2_index
ruleorder: create_ref_links_for_hic_alignment > ref_faidx
ruleorder: create_ref_links_for_hic_alignment > get_seq_len
localrules: create_ref_links_for_hic_alignment

use rule create_local_links as create_ref_links_for_hic_alignment with:
    input:
        fasta=lambda wildcards: config["out_dir"] / ("%s/%s/%s.%s.%s.fasta" % (stage_dict["hic_alignment"].prev_stage,
                                                                               get_prev_stage_parameters(wildcards.parameters),
                                                                               wildcards.genome_prefix,
                                                                               stage_dict["hic_alignment"].prev_stage,
                                                                               wildcards.haplotype)),
        fai=lambda wildcards: config["out_dir"] / ("%s/%s/%s.%s.%s.fasta.fai" % (stage_dict["hic_alignment"].prev_stage,
                                                                                 get_prev_stage_parameters(wildcards.parameters),
                                                                                 wildcards.genome_prefix,
                                                                                 stage_dict["hic_alignment"].prev_stage,
                                                                                 wildcards.haplotype)),
        len=lambda wildcards: config["out_dir"] / ("%s/%s/%s.%s.%s.len" % (stage_dict["hic_alignment"].prev_stage,
                                                                           get_prev_stage_parameters(wildcards.parameters),
                                                                           wildcards.genome_prefix,
                                                                           stage_dict["hic_alignment"].prev_stage,
                                                                           wildcards.haplotype)),
        bwa_ann=lambda wildcards: config["out_dir"] / ("%s/%s/%s.%s.%s.fasta.ann" % (stage_dict["hic_alignment"].prev_stage,
                                                                                     get_prev_stage_parameters(wildcards.parameters),
                                                                                     wildcards.genome_prefix,
                                                                                     stage_dict["hic_alignment"].prev_stage,
                                                                                     wildcards.haplotype)),
        bwa_amb=lambda wildcards: config["out_dir"] / ("%s/%s/%s.%s.%s.fasta.amb" % (stage_dict["hic_alignment"].prev_stage,
                                                                                     get_prev_stage_parameters(wildcards.parameters),
                                                                                     wildcards.genome_prefix,
                                                                                     stage_dict["hic_alignment"].prev_stage,
                                                                                     wildcards.haplotype)),
        bwa_pac=lambda wildcards: config["out_dir"] / ("%s/%s/%s.%s.%s.fasta.pac" % (stage_dict["hic_alignment"].prev_stage,
                                                                                     get_prev_stage_parameters(wildcards.parameters),
                                                                                     wildcards.genome_prefix,
                                                                                     stage_dict["hic_alignment"].prev_stage,
                                                                                     wildcards.haplotype)),
        bwa_bwt=lambda wildcards: config["out_dir"] / ("%s/%s/%s.%s.%s.fasta.bwt.2bit.64" % (stage_dict["hic_alignment"].prev_stage,
                                                                                             get_prev_stage_parameters(wildcards.parameters),
                                                                                             wildcards.genome_prefix,
                                                                                             stage_dict["hic_alignment"].prev_stage,
                                                                                             wildcards.haplotype)),
        bwa_0123=lambda wildcards: config["out_dir"] / ("%s/%s/%s.%s.%s.fasta.0123" % (stage_dict["hic_alignment"].prev_stage,
                                                                                       get_prev_stage_parameters(wildcards.parameters),
                                                                                       wildcards.genome_prefix,
                                                                                       stage_dict["hic_alignment"].prev_stage,
                                                                                       wildcards.haplotype)),
        log_dir=lambda wildcards: ancient(config["out_dir"] / "hic_alignment/log/")
    output:
        fasta=config["out_dir"] / "hic_alignment/{parameters}/{genome_prefix}.hic_alignment.{haplotype, hap[^./]+}.fasta",
        fai=config["out_dir"] / "hic_alignment/{parameters}/{genome_prefix}.hic_alignment.{haplotype, hap[^./]+}.fasta.fai",
        len=config["out_dir"] / "hic_alignment/{parameters}/{genome_prefix}.hic_alignment.{haplotype, hap[^./]+}.len",
        bwa_ann=config["out_dir"] / "hic_alignment/{parameters}/{genome_prefix}.hic_alignment.{haplotype, hap[^./]+}.fasta.ann",
        bwa_amb=config["out_dir"] / "hic_alignment/{parameters}/{genome_prefix}.hic_alignment.{haplotype, hap[^./]+}.fasta.amb",
        bwa_pac=config["out_dir"] / "hic_alignment/{parameters}/{genome_prefix}.hic_alignment.{haplotype, hap[^./]+}.fasta.pac",
        bwa_bwt=config["out_dir"] / "hic_alignment/{parameters}/{genome_prefix}.hic_alignment.{haplotype, hap[^./]+}.fasta.bwt.2bit.64",
        bwa_0123=config["out_dir"] / "hic_alignment/{parameters}/{genome_prefix}.hic_alignment.{haplotype, hap[^./]+}.fasta.0123",
    log:
        ln=config["out_dir"] / "log/create_ref_links_for_stages.hic_alignment.{parameters}.{genome_prefix}.{haplotype}.ln.log",