#!/usr/bin/env python
__author__ = 'mahajrod'
import sys
import argparse
from functools import partial
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

from RouToolPa.Parsers.AGP import CollectionAGP

SCAFFOLD_COL = "scaffold"
START_COL = "start"
END_COL = "end"
PART_NUMBER = "part_number"
PART_TYPE_COL = "part_type"
PART_ID_COL = "part_id/gap_length"
PART_START_COL = "part_start/gap_type"
PART_END_COL = "part_end/linkage"
ORIENTATION_COL = "orientation/evidence"
FIVE_PRIME_TELOMERE_COL="five_prime_telomere"
THREE_PRIME_TELOMERE_COL="three_prime_telomere"

def detect_splits_by_internal_telomeres(df): # function intended to deal with single scaffold df, i.e. df generated by groupby with grouping by scaffold

    tmp_df = df
    tmp_df["FIVE_PRIME_SPLIT"] = False
    tmp_df.loc[list(df[FIVE_PRIME_TELOMERE_COL]), "FIVE_PRIME_SPLIT"] = True
    tmp_df["FIVE_PRIME_SPLIT"].iloc[0] = False
    tmp_df["THREE_PRIME_SPLIT"] = False
    tmp_df.loc[list(df[THREE_PRIME_TELOMERE_COL]), "THREE_PRIME_SPLIT"] = True
    tmp_df["THREE_PRIME_SPLIT"].iloc[-1] = False
    tmp_df["SPLIT_INDEX"] = 0

    if sum(tmp_df["FIVE_PRIME_SPLIT"]) + sum(tmp_df["THREE_PRIME_SPLIT"]) == 0:
        return tmp_df
    tmp_df.reset_index(drop=False, inplace=True)

    split = 1
    #print(tmp_df)
    number_of_rows = len(tmp_df)
    for row in range(0, len(tmp_df)):
        if tmp_df.loc[row, "SPLIT_INDEX"] == -1: # '-1' labels gaps to be deleted
            continue
        if (not tmp_df.loc[row, "FIVE_PRIME_SPLIT"]) and (not tmp_df.loc[row, "THREE_PRIME_SPLIT"]):
            tmp_df.loc[row, "SPLIT_INDEX"] = split
            continue
        if tmp_df.loc[row, "FIVE_PRIME_SPLIT"]:
            tmp_df.loc[row, "SPLIT_INDEX"] = split  + 1

            if row - 1 >= 0:
                if (tmp_df.loc[row - 1, PART_TYPE_COL] == "N") or (tmp_df.loc[row - 1, PART_TYPE_COL] == "U"):
                    tmp_df.loc[row - 1, "SPLIT_INDEX"] = -1

            split += 1

        if tmp_df.loc[row, "THREE_PRIME_SPLIT"]:
            tmp_df.loc[row, "SPLIT_INDEX"] = split

            if row + 1 < number_of_rows:
                if (tmp_df.loc[row + 1, PART_TYPE_COL] == "N") or (tmp_df.loc[row + 1, PART_TYPE_COL] == "U"):
                    tmp_df.loc[row + 1, "SPLIT_INDEX"] = -1

            split += 1
    tmp_df = tmp_df.set_index(SCAFFOLD_COL)
    return tmp_df

def check_for_telomeres(row, five_prime_blacklist, three_prime_blacklist):
    result_list = pd.Series([False, False])
    #print(row)
    #print(row.loc[PART_ID_COL], row.loc[ORIENTATION_COL])
    if row.loc[PART_ID_COL] in five_prime_blacklist:
        if row.loc[ORIENTATION_COL] == "+":
            result_list.iloc[0] = True
        elif row.loc[ORIENTATION_COL] == "-":
            result_list.iloc[1] = True
        else:
            pass
    if row.loc[PART_ID_COL] in three_prime_blacklist:
        if row.loc[ORIENTATION_COL] == "+":
            result_list.iloc[1] = True
        elif row.loc[ORIENTATION_COL] == "-":
            result_list.iloc[0] = True
        else:
            pass
    return result_list

def apply_changes(records_df): # function intended to deal with single scaffold df, i.e. df generated by groupby with grouping by scaffold
    tmp_df = records_df
    tmp_df.set_index(SCAFFOLD_COL, inplace=True)
    start = tmp_df[START_COL].iloc[0]
    tmp_df[START_COL] = tmp_df[START_COL] - start + 1
    tmp_df[END_COL] = tmp_df[END_COL] - start + 1
    tmp_df[PART_NUMBER] = range(1, len(tmp_df ) + 1)

    return tmp_df

def read_blacklist(filename):
    try:
        tmp_list = list(pd.read_csv(filename, sep="\t", header=None).squeeze())
    except pd.errors.EmptyDataError:
        tmp_list = []
    return tmp_list

parser = argparse.ArgumentParser()

parser.add_argument("-a", "--agp", action="store", dest="agp", default=sys.stdin,
                    help="Input agp file. Default: stdin")
parser.add_argument("--five_prime_blacklist", action="store", dest="five_prime_blacklist", required=True,
                    type=read_blacklist,
                    help="File with contigs blacklisted to have 5' joins. Required.")
parser.add_argument("--three_prime_blacklist", action="store", dest="three_prime_blacklist", required=True,
                    type=read_blacklist,
                    help="File with contigs blacklisted to have 3' joins. Required.")
parser.add_argument("-s", "--separator", action="store", dest="separator", default="@",
                    help="Separator between original scaffold id and split. Default: '@'")
parser.add_argument("-p", "--output_prefix", action="store", dest="output_prefix", required=True,
                    help="Prefix of output files")

args = parser.parse_args()

intermediate_file = "{0}.telomere.split.intermediate".format(args.output_prefix)
final_file = "{0}.telomere.split.final".format(args.output_prefix)
final_agp_file = "{0}.telomere.split.final.agp".format(args.output_prefix)
final_len_file = "{0}.telomere.split.final.len".format(args.output_prefix)
final_syn_file = "{0}.telomere.split.final.syn".format(args.output_prefix)
final_renamed_agp_file = "{0}.telomere.split.final.renamed.agp".format(args.output_prefix)
final_renamed_len_file = "{0}.telomere.split.final.renamed.len".format(args.output_prefix)
final_renamed_stats_file = "{0}.telomere.split.final.renamed.stats".format(args.output_prefix)

collection_agp = CollectionAGP(in_file=args.agp)
collection_agp.records["five_prime_telomere"] = False
collection_agp.records["three_prime_telomere"] = False
collection_agp.records[["five_prime_telomere", "three_prime_telomere"]] = collection_agp.records.apply(partial(check_for_telomeres, five_prime_blacklist=args.five_prime_blacklist,
                                                                                            three_prime_blacklist=args.three_prime_blacklist),
                                                                                    axis=1, result_type='expand')

collection_agp.records = collection_agp.records.groupby(SCAFFOLD_COL, as_index=False).apply(detect_splits_by_internal_telomeres).reset_index(level=0, drop=True)
collection_agp.records.to_csv(intermediate_file, sep="\t", index=True)

collection_agp.records = collection_agp.records[collection_agp.records["SPLIT_INDEX"] != -1].reset_index(drop=False)
collection_agp.records[SCAFFOLD_COL] = collection_agp.records[SCAFFOLD_COL] + args.separator + collection_agp.records["SPLIT_INDEX"].astype(str)
collection_agp.records = collection_agp.records.groupby(by=SCAFFOLD_COL, as_index=False).apply(apply_changes).reset_index(level=0, drop=True)
collection_agp.records.to_csv(final_file, sep="\t", index=True)
collection_agp.get_seq_len()
collection_agp.records = collection_agp.records[[START_COL, END_COL, PART_NUMBER, PART_TYPE_COL, PART_ID_COL, PART_START_COL,
                           PART_END_COL,ORIENTATION_COL,]]

collection_agp.records.to_csv(final_agp_file, sep="\t", index=True, header=False)
collection_agp.length_df.to_csv(final_len_file, sep="\t", index=True, header=False)

syn_df = collection_agp.length_df.copy(deep=True)
syn_df["syn"] = ["ps_scaffold_{0}".format(i) for i in range(0, len(syn_df))]
syn_df[["syn"]].to_csv(final_syn_file, sep="\t", index=True, header=False)

syn_dict = syn_df["syn"].to_dict()

collection_agp.records.rename(index=syn_dict, inplace=True)
collection_agp.length_df.rename(index=syn_dict, inplace=True)
collection_agp.records.to_csv(final_renamed_agp_file, sep="\t", index=True, header=False)
collection_agp.length_df.to_csv(final_renamed_len_file, sep="\t", index=True, header=False)

final_stat_df = pd.DataFrame(0, columns=["placed_sequences", "placed_bp", "unplaced_sequences", "unplaced_bp", "gap_bp", "gap_sequences"],
                             index=["stats"])
contigs = sum(~collection_agp.records[PART_TYPE_COL].isin(("U", "N")))
count_df = collection_agp.records["start"].groupby(by=SCAFFOLD_COL).count()
gap_df = collection_agp.records[collection_agp.records[PART_TYPE_COL].isin(("U", "N"))]

final_stat_df.loc["stats", "gap_bp"] = sum(gap_df["end"] - gap_df["start"] + 1)
final_stat_df.loc["stats", "placed_bp"] = sum(collection_agp.records.loc[count_df[count_df > 1].index].groupby(by=SCAFFOLD_COL).apply(lambda df: df[END_COL].iloc[-1]))
final_stat_df.loc["stats", "unplaced_bp"] = sum(collection_agp.records.loc[count_df[count_df == 1].index][END_COL])
final_stat_df.loc["stats", "unplaced_sequences"] = sum(count_df == 1)
final_stat_df.loc["stats", "placed_sequences"] = contigs - final_stat_df.loc["stats", "unplaced_sequences"]
final_stat_df.loc["stats", "gap_sequences"] = sum(collection_agp.records[PART_TYPE_COL].isin(("U", "N")))

final_stat_df.to_csv(final_renamed_stats_file, sep="\t", index=False, header=True)