jobs: 100
use-conda: false
cluster: "sbatch {resources.node_options} --partition={resources.queue} -t {resources.time} --mem={resources.mem} -c {resources.cpus} --parsable -o {log.cluster_log} -e {log.cluster_err}"
