"skip_read_qc": False
"skip_filter_reads": False
"skip_busco": False
"skip_gcp": True
"skip_fcs": False
"skip_fcs_adaptor": False
"skip_kraken": False
"skip_phasing": False
"skip_prescaf_pretext": True
"skip_postscaf_pretext": True

"skip_both_pretext": False
"skip_pretext_10k_1k_tracks": False
"skip_pretext_1000k_100k_tracks": True
"skip_nanoqc": False
"skip_nanoplot": False
"skip_wga": False
"skip_higlass": True
"skip_variantcalling": True
"skip_hic_file": False
"skip_all_pretext": False
"skip_krater": True
"skip_kmer": False
"skip_ragtag": False
"skip_gathering": True
"skip_trf": False
"skip_combined_hic": False
"skip_combined_contig_hic": False

"skip_draft_qc_pretext": False
"skip_draft_qc_hic_file": False
"skip_draft_qc_ragtag": False
"skip_draft_qc_wga": False

"skip_gap_closing_pretext": False
"skip_gap_closing_hic_file": False
"skip_gap_closing_ragtag": False
"skip_gap_closing_wga": False
