#---- Bioconda config for salsa2 ----

"name": "simulate_pcr"
"channels":
  - "bioconda"
  - "conda-forge"
  - "anaconda"
"dependencies":
  - "blast=2.2.31"
  - "perl-bioperl"
  - "perl-lwp-simple"
  - "perl-getopt-long"
