#---- Bioconda config ----
#TODO: check external_tools and versions
"name": "yggbase"
"channels":
  - "bioconda"
  - "conda-forge"
  - "anaconda"
"dependencies":
  - "singularity=3.5"
  - "python=3.8"
