#---- Bioconda config ----
#TODO: check tools and versions
"name": "yggbase"
"channels":
  - "mahajrod"
  - "bioconda"
  - "conda-forge"
  - "anaconda"
"dependencies":
  - "python>=3.8"
  - "fastqc>=0.11"
  - "multiqc"
  - "hifiasm"
  - "minimap2"
  - "purge_dups"
  - "yahs"
  - "quast"
  - "gfatools"
  - "cutadapt=3.4"
  - "libopenblas"
  - "bwa=0.7.17"
  - "picard>=2.5"
  - "pretext-suite"
  - "samtools>=1.10"
  - "mosdepth>=0.3.1"
  - "numpy<1.24" # NumPy v 1.24 and higher is incompatible with pairtools
  - "scipy"
  - "pandas>=1.2"
  - "matplotlib"
  - "bedtools>=2.26"
  - "tabix"
  - "statsmodels>=0.12"
  - "pip"
  - "xlsxwriter"
  - "R"
  - "r-minpack.lm"
  - "r-argparse"
  - "r-ggplot2"
  - "r-scales"
  - "genomescope2"
  - "kraken2"
  - "smudgeplot"
  - "pairtools"
  - "parallel"
  - "routoolpa>=0.100"
  - "mavr>=0.97"
  - "jellyfish>=2"
  - "krater>=2.7.9"
  - "mace>=1.1.6"
  - "biopython"
  - "pyfastaq"
  - "seqtk"
  - "blast"
