#---- Bioconda config ----

#TODO: check tools and versions
"name": "kmer"
"channels":
  - "mahajrod"
  - "bioconda"
  - "conda-forge"
  - "anaconda"
"dependencies":
  - "python=3.10"
  - "meryl>=1.4"
  - "merqury"
  - "yak"
  - "krater"
  - pip:
      - "distinctipy"
