#---- Bioconda config ----

#TODO: check tools and versions
"name": "yggbase"
"channels":
  - "mahajrod"
  - "bioconda"
  - "conda-forge"
  - "anaconda"
"dependencies":
  - "python=3.9"
  - "fastqc>=0.11"
  - "blas=*=*mkl"
  - "multiqc"
  - "hifiasm"
  - "minimap2"
  - "purge_dups"
  - "yahs"
  - "quast"
  - "gfatools"
  - "cutadapt=4.6"
  - "libopenblas"
  - "bwa=0.7.17"
  - "picard>=2.5"
  - "pretext-suite"
  - "samtools>=1.10"
  - "mosdepth>=0.3.1"
  - "numpy"
  - "scipy=1.08"
  - "pandas>=1.2"
  - "matplotlib"
  - "bedtools>=2.26"
  - "tabix"
  - "statsmodels>=0.12"
  - "pip"
  - "xlsxwriter"
  - "R"
  - "r-minpack.lm"
  - "r-argparse"
  - "r-ggplot2"
  - "r-scales"
  - "genomescope2"
  - "kraken2"
  - "smudgeplot"
  - "parallel"
  - "routoolpa>=0.111"
  - "mavr>=0.112"
  - "jellyfish>=2"
  - "krater>=2.7.11"
  - "mace>=1.1.12"
  - "biopython"
  - "pyfastaq"
  - "seqtk"
  - "blast"
  - "cooler"
  - "bwa-mem2"
  - "trf"
  - "last"
  - "fastx_toolkit"
  - "tabulate"
  - "trimmomatic"

