channels:
  - "conda-forge"
  - "bioconda"
  - "defaults"
dependencies:
  - "python=3.6"
  - "samtools=1.11"
  - "cd-hit=4.8.1"
  - "minimap2=2.19"
  - "hifiasm=0.19.5"
  - "mafft=7.520"
  - "biopython"
  - "matplotlib"
  - "dna_features_viewer=3.1.2"
  - "pandas"
  - "bedtools=2.31.0"
  - "pillow=6.2.1"
  - "bcbio-gff=0.7.0"
  - "mitos>2.1.0"
