#---- Bioconda config ----
#TODO: check tools and versions
"name": "nanopore"
"channels":
  - "mahajrod"
  - "bioconda"
  - "conda-forge"
  - "anaconda"
"dependencies":
  - "numpy==1.23" # NanoQC uses np.bool8 which is depricated in newer versions
  - "nanoqc"
  - "chopper"
  - "filtlong"
  - "porechop_abi"
  - "nanoplot"
