#---- Bioconda config ----
#TODO: check external_tools and versions
"name": "nanopore"
"channels":
  - "mahajrod"
  - "bioconda"
  - "conda-forge"
  - "anaconda"
"dependencies":
  - "nanoqc"
  - "chopper"
  - "filtlong"
  - "porechop_abi"
  - "nanoplot"
